trigger:
  branches:
    include:
      - none   # Manual trigger only
    exclude:
      - features/**

pool:
  vmImage: ubuntu-latest

variables:
  - group: ArgoCD-Variable

stages:
- stage: Build
  displayName: Build and Push Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Npm@1
      displayName: Install Dependencies
      inputs:
        command: ci   

    - task: Npm@1
      displayName: Build App
      inputs:
        command: custom
        customCommand: run build

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: $(Docker-SC)

    - task: Docker@2
      displayName: Docker Build
      inputs:
        command: build
        containerRegistry: $(Docker-SC)
        repository: $(IMAGE_REPO)
        Dockerfile: $(Build.SourcesDirectory)/Dockerfile
        buildContext: $(Build.SourcesDirectory)
        arguments: '--progress=plain'
        tags: |
          $(IMAGE_TAG)

    - task: Docker@2
      displayName: Docker Push
      inputs:
        command: push
        containerRegistry: $(Docker-SC)
        repository: $(IMAGE_REPO)
        tags: |
          $(IMAGE_TAG)
    
    - task: Kubernetes@1
      displayName: Deploy Manifests to AKS
      inputs:
        connectionType: Azure Resource Manager
        azureSubscriptionEndpoint: '$(ARM-SC)'
        azureResourceGroup: '$(aksRG)'
        kubernetesCluster: '$(aksCluster)'
        namespace: nike-landing
        command: apply
        useConfigurationFile: true
        configuration: |
          kubectl apply -f helm/nike-landing/templates/deployment.yaml
          kubectl apply -f helm/nike-landing/templates/service.yaml
          kubectl apply -f helm/nike-landing/templates/ingress.yaml