apiVersion: v1
kind: Service
metadata:
name: {{ include "nike-landing.fullname" . }}
labels:
{{- include "nike-landing.labels" . | nindent 4 }}
spec:
type: {{ .Values.service.type }}
selector:
{{- include "nike-landing.selectorLabels" . | nindent 4 }}
ports:
- port: {{ .Values.service.port }}
targetPort: {{ .Values.service.targetPort }}
protocol: TCP
name: http